import streamlit as st
import sqlite3
import pandas as pd
import joblib
import os
import hashlib
import plotly.express as px
from datetime import datetime
from fpdf import FPDF
from contextlib import contextmanager

# --- 1. CONFIG & SYSTEM DATABASE ---
DB_NAME = "credit_risk_elite_final.db"
# Source of truth for feature order
REQUIRED_COLS = ['name', 'income', 'loan_amount', 'existing_debt', 'duration_months', 'credit_score', 'employment_years']
DATE_FORMAT = "%Y-%m-%d %H:%M"

def hash_pw(password): 
    return hashlib.sha256(str.encode(password)).hexdigest()

@contextmanager
def db_connection():
    conn = sqlite3.connect(DB_NAME)
    try: yield conn
    finally: conn.close()

def generate_pdf(name, pd_val, loss, level, decision, driver, officer):
    clean_decision = decision.replace("✅ ", "").replace("⚠️ ", "").replace("❌ ", "")
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, "Credit Risk Intelligence Analysis Report", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", '', 12)
    # Fix #4: Replace non-latin chars for PDF stability
    safe_name = name.encode('ascii', 'ignore').decode('ascii')
    pdf.cell(200, 10, f"Customer: {safe_name}", ln=True)
    pdf.cell(200, 10, f"Analyzing Officer: {officer}", ln=True)
    pdf.cell(200, 10, f"Date: {datetime.now().strftime(DATE_FORMAT)}", ln=True)
    pdf.ln(5)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, "AI Risk Assessment Metrics:", ln=True)
    pdf.set_font("Arial", '', 12)
    pdf.cell(200, 10, f"- Probability of Default: {pd_val}%", ln=True)
    pdf.cell(200, 10, f"- Expected Loss: GHS {loss}", ln=True)
    pdf.cell(200, 10, f"- Recommendation: {clean_decision} ({level} Risk)", ln=True)
    pdf.cell(200, 10, f"- Primary Risk Driver: {driver}", ln=True)
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 10, "Disclaimer: This report is generated by an AI Decision Engine based on historical data.")
    return pdf.output(dest='S').encode('latin-1', errors='replace')

def init_db():
    with db_connection() as conn:
        c = conn.cursor()
        c.execute('''CREATE TABLE IF NOT EXISTS history 
                     (date TEXT, name TEXT, pd REAL, loss REAL, level TEXT, decision TEXT, officer TEXT, consent_log TEXT)''')
        c.execute('CREATE TABLE IF NOT EXISTS users (username TEXT PRIMARY KEY, password TEXT, role TEXT)')
        c.execute("INSERT OR IGNORE INTO users VALUES ('admin', ?, 'Admin')", (hash_pw('knust2026'),))
        conn.commit()

init_db()

# --- 2. THE HARDENED ENGINE (Fixed #1, #2, #3) ---
def analyze_risk(data_dict, meta):
    """
    Fixed #3: Now accepts a DICTIONARY to ensure feature alignment 
    and prevents silent failure.
    """
    # Fix #1: Model Presence Validation
    model = meta.get('model')
    if model is None:
        raise ValueError("Critical Error: ML Model object not found in metadata.")

    # Fix #2: Importance Type Safety
    importance_raw = meta.get('importance', {})
    importance = dict(importance_raw) if hasattr(importance_raw, 'to_dict') else importance_raw
    
    # Fix #3: Explicit Feature Alignment
    # We rebuild the input vector based on the model's expected feature order
    model_features = meta.get('features', REQUIRED_COLS[1:])
    try:
        aligned_data = [data_dict[f] for f in model_features]
    except KeyError as e:
        raise KeyError(f"Data Mismatch: Missing required feature {e}")

    # Prediction
    pd_raw = model.predict_proba([aligned_data])[0][1]
    pd_val = round(pd_raw * 100, 2)
    loss = round(pd_raw * data_dict.get('loan_amount', 0), 2)
    
    level = "LOW" if pd_val <= 30 else "MEDIUM" if pd_val <= 60 else "HIGH"
    decision = "✅ Approve" if level == "LOW" else "⚠️ Review" if level == "MEDIUM" else "❌ Reject"
    
    # Fix #1: Crash-proof Explainability
    try:
        impacts = {f: data_dict[f] * importance.get(f, 0) for f in model_features}
        top_driver = max(impacts, key=impacts.get).replace('_', ' ').title()
    except Exception:
        top_driver = "Risk Factors Distributed Across Profile"
    
    return pd_val, loss, level, decision, top_driver

# --- 3. UI & AUTHENTICATION ---
st.set_page_config(page_title="Credit Risk Elite Suite", layout="wide", page_icon="🛡️")

if 'auth' not in st.session_state:
    st.session_state.update({'auth': False, 'user': None, 'role': None, 'last_result': None})

if not st.session_state.auth:
    st.title("🔐 Enterprise Portal Authentication")
    u, p = st.text_input("User ID"), st.text_input("Passkey", type="password")
    if st.button("Secure Login"):
        with db_connection() as conn:
            c = conn.cursor()
            c.execute("SELECT password, role FROM users WHERE username = ?", (u,))
            res = c.fetchone()
            if res and res[0] == hash_pw(p):
                st.session_state.update({'auth': True, 'user': u, 'role': res[1]})
                st.rerun()
            else: st.error("Authentication Failure")
else:
    st.title(f"🛡️ {st.session_state.role} Dashboard | Active User: {st.session_state.user}")
    
    # --- 4. OPERATIONS (Officer / Admin) ---
    if st.session_state.role in ["Officer", "Admin"]:
        mode = st.radio("Task Selection", ["Single Application", "Batch Scoring (CSV)"])
        
        if mode == "Single Application":
            with st.form("single_app"):
                c1, c2 = st.columns(2)
                with c1:
                    name = st.text_input("Customer Full Name")
                    inc = st.number_input("Monthly Income (GHS)", 1, value=5000)
                    loan = st.number_input("Requested Loan", 1, value=10000)
                with c2:
                    debt = st.number_input("Existing Monthly Debt", 0, value=500)
                    cred = st.slider("Credit Score", 300, 850, 650)
                    dur = st.selectbox("Term (Months)", [12, 24, 36])
                    exp = st.number_input("Employment Years", 0, 50, 5)
                consent = st.checkbox("Legal Data Consent Confirmed")
                submitted = st.form_submit_button("Run Analysis")
                
            if submitted:
                # Fix #7: Pre-load validation
                if not os.path.exists('loan_model_enterprise.pkl'):
                    st.error("System Error: AI Model required. Run train_model.py")
                elif not name or not consent:
                    st.warning("Validation Error: Name and Consent required.")
                else:
                    try:
                        meta = joblib.load('loan_model_enterprise.pkl')
                        # Map inputs to dict to fix #3
                        data_in = {
                            'income': inc, 'loan_amount': loan, 'existing_debt': debt, 
                            'duration_months': dur, 'credit_score': cred, 'employment_years': exp
                        }
                        pd_v, l_v, lv, dec, driver = analyze_risk(data_in, meta)
                        
                        # Store in session state for UI persistence (Fix #5)
                        st.session_state.last_result = {"name": name, "pd": pd_v, "loss": l_v, "level": lv, "dec": dec, "driver": driver}
                        
                        st.markdown("---")
                        st.subheader(f"Analysis Results: {name}")
                        m1, m2, m3 = st.columns(3)
                        m1.metric("Risk Probability", f"{pd_v}%")
                        m2.metric("Expected Loss", f"GHS {l_v}")
                        m3.subheader(f"Decision: {dec}")
                        st.info(f"**AI Insight:** Primary risk driver is **{driver}**.")
                        
                        pdf_data = generate_pdf(name, pd_v, l_v, lv, dec, driver, st.session_state.user)
                        st.download_button("📄 Download Official Report", data=pdf_data, file_name=f"Report_{name}.pdf")
                        
                        with db_connection() as conn:
                            c = conn.cursor()
                            c.execute("INSERT INTO history VALUES (?,?,?,?,?,?,?,?)", 
                                      (datetime.now().strftime(DATE_FORMAT), name, pd_v, l_v, lv, dec, st.session_state.user, "Officer-Signed"))
                            conn.commit()
                    except Exception as e:
                        st.error(f"Analysis Failed: {str(e)}")

        else: # BATCH SCORING
            up = st.file_uploader("Upload Bulk CSV List", type="csv")
            if up:
                df_up = pd.read_csv(up)
                if not all(col in df_up.columns for col in REQUIRED_COLS):
                    st.error(f"Structure Error: Missing columns {REQUIRED_COLS}")
                elif df_up[REQUIRED_COLS[1:]].isnull().values.any():
                    st.error("Data Error: CSV contains missing numeric values.")
                else:
                    if st.button("⚡ Execute & Log Batch Scoring"):
                        if not os.path.exists('loan_model_enterprise.pkl'):
                            st.error("Model Missing!")
                        else:
                            try:
                                meta = joblib.load('loan_model_enterprise.pkl')
                                final_results = []
                                with db_connection() as conn:
                                    c = conn.cursor()
                                    for _, row in df_up.iterrows():
                                        try:
                                            # Map row to dict to fix #3
                                            pd_v, l_v, lv, dec, driver = analyze_risk(row.to_dict(), meta)
                                            # Fix #6: Uniform Date Format
                                            c.execute("INSERT INTO history VALUES (?,?,?,?,?,?,?,?)", 
                                                      (datetime.now().strftime(DATE_FORMAT), row['name'], pd_v, l_v, lv, dec, st.session_state.user, "Batch-Processed"))
                                            final_results.append({'Name': row['name'], 'Risk%': pd_v, 'Decision': dec, 'Driver': driver})
                                        except Exception:
                                            continue
                                    conn.commit()
                                
                                batch_res_df = pd.DataFrame(final_results)
                                st.success(f"Logged {len(batch_res_df)} records to Audit Log.")
                                st.dataframe(batch_res_df)
                                st.download_button("📥 Download Scored CSV", batch_res_df.to_csv(index=False), "batch_results.csv")
                            except Exception as e:
                                st.error(f"Batch Processing Failed: {e}")

    # --- 5. ANALYTICS ---
    if st.session_state.role in ["Manager", "Admin"]:
        st.markdown("---")
        t1, t2, t3 = st.tabs(["📊 Portfolio BI", "📂 Audit Trail", "👤 System Admin"])
        with db_connection() as conn:
            df = pd.read_sql("SELECT * FROM history", conn)
        
        with t1:
            if not df.empty:
                k1, k2, k3 = st.columns(3)
                k1.metric("Average Risk", f"{df['pd'].mean():.1f}%")
                k2.metric("Exposure", f"GHS {df['loss'].sum():.0f}")
                k3.metric("Approval Rate", f"{(len(df[df['decision'].str.contains('Approve')])/len(df))*100:.1f}%")
                st.plotly_chart(px.histogram(df, x="pd", color="level", title="Risk Distribution Analysis"))
        
        with t2:
            st.dataframe(df.sort_values(by="date", ascending=False), use_container_width=True)

        with t3:
            if st.session_state.role == "Admin":
                with st.form("user_add"):
                    nu, np, nr = st.text_input("New User ID"), st.text_input("Access Password", type="password"), st.selectbox("Role Assignment", ["Officer", "Manager", "Admin"])
                    if st.form_submit_button("Provision User"):
                        with db_connection() as conn:
                            c = conn.cursor()
                            c.execute("INSERT OR IGNORE INTO users VALUES (?,?,?)", (nu, hash_pw(np), nr))
                            conn.commit()
                            st.success("User Created Successfully.")

    if st.sidebar.button("Logout"):
        st.session_state.auth = False
        st.session_state.last_result = None
        st.rerun()